In [13]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../data/news.db')

# Load tabel news ke DataFrame
df = pd.read_sql_query("SELECT * FROM news", conn)
conn.close()

# Eksplorasi awal
print("Jumlah data:", df.shape)
print("\nKolom:", df.columns.tolist())
print("\n5 data pertama:")
df.head()

Jumlah data: (1705, 7)

Kolom: ['id', 'title', 'source', 'link', 'tanggal', 'description', 'guid']

5 data pertama:

,id,title,source,link,tanggal,description,guid
0,1,"Trump Nyinyir Lagi: Tolong Beritahu Paus Leo, ...",CNN Indonesia,https://news.google.com/rss/articles/CBMi0gFBV...,"Wed, 15 Apr 2026 06:15:03 GMT","<ol><li><a href=""https://news.google.com/rss/a...",CBMi0gFBVV95cUxQWXBJVmlyZGMteWRFcVdraTgtVThYdG...
1,2,"AS Kirim Kapal Perang ke Selat Hormuz, Eks KSA...",Kompas.tv,https://news.google.com/rss/articles/CBMi1gFBV...,"Tue, 14 Apr 2026 12:11:00 GMT","<ol><li><a href=""https://news.google.com/rss/a...",CBMi1gFBVV95cUxONXZLV2NVQVpycXBpM0tpbmNoRXpWQ0...
2,3,"Prabowo Bertemu Macron di Istana Elysee, Bahas...",CNBC Indonesia,https://news.google.com/rss/articles/CBMixAFBV...,"Tue, 14 Apr 2026 16:20:00 GMT","<ol><li><a href=""https://news.google.com/rss/a...",CBMixAFBVV95cUxOaTN1VUhLSmpBdWtqVGFiQlNmcE9lZk...
3,4,Isi Chat Pelecehan Seksual 16 Mahasiswa Hukum ...,Mistar.id,https://news.google.com/rss/articles/CBMilAFBV...,"Tue, 14 Apr 2026 05:47:00 GMT","<ol><li><a href=""https://news.google.com/rss/a...",CBMilAFBVV95cUxNa2xMSWRkdDZ2MEF3b1RCdWZvWE9uRE...
4,5,"7 Keunggulan Oghab 44, Bandara Bawah Tanah Ira...",SINDOnews Internasional,https://news.google.com/rss/articles/CBMi5gFBV...,"Wed, 15 Apr 2026 03:30:30 GMT","<ol><li><a href=""https://news.google.com/rss/a...",CBMi5gFBVV95cUxQRE1mZ1hYb0V4dktHem8yR0xlTnU5bm...

In [14]:
# Cek data kosong
print(df.isnull().sum())

# Cek contoh isi description (masih HTML)
print(df['description'][0])

id             0
title          0
source         0
link           0
tanggal        0
description    0
guid           0
dtype: int64
<ol><li><a href="https://news.google.com/rss/articles/CBMi0gFBVV95cUxQWXBJVmlyZGMteWRFcVdraTgtVThYdG1FcWpna0piTkUzR1EwSjN0WVhpR0lBMF9RS3Fvb2V1U3UteXlma1Q5TUtCcVFmamVsN3kyanQ3M0FyVVRpTlZZSjFvWVRHd0JhdUpjNjFqSjkzcXdOU2dqSHFwMEY0UEpYVUFScVBXMHVya3U0Ti01NHFLQ18wZWo0amdZczgwbVRCbmdtYVowaF8zWE42WE0zcXpBdDhxWUdGektzU05PazVQdXRFd1RkNE9pRmVFS0poVUHSAdcBQVVfeXFMUGZIVnNESUs4Tm1VZmtYZ2pjMXJhbHc2X0traUFiaEtRdzBhMjJDXzB3RGdNX2JoVmc4dEpEYXJjRU85VHo5YkVHdnNYWTRlWC1wRmxsUHlWUm1vaTI0LWFSZ3VsZVhRX2ZUcHQ5dDRPdERxMXdHRGtnRWlpZmlTSDVsSHltNHFhZWZIMkxMVEZNTkhpbVBWcE1rWUo1OEFVTVowcmtia0VzNzJicm41WlFuVDlLaWFDNlA1ZlM1M05zYm9YanJmVjhZM1FoUWpTeWlJWDZ6Wnc?oc=5" target="_blank">Trump Nyinyir Lagi: Tolong Beritahu Paus Leo, Iran Bunuh 42.000 Orang</a>&nbsp;&nbsp;<font color="#6f6f6f">CNN Indonesia</font></li><li><a href="https://news.google.com/rss/articles/CBMilgFBVV95cUxOSlE5aDlMcEpkeGkzTjJoU3ZFZEJpQWZTU0dqWFpnN0hrY1VHZkNfLXdJQ3IxenBCVmFvd25ubGVtQVU2Mkx2ODNvdEswMndOUDc1UmpBUnlpS3lVZ09oQUgzOHQ3Ty1CS1YyTTV5Z1BfeU43Q2ZSSjVKN1dRdXZsMDdZY0VhTUNtaGpDN2FFTVVOYWxKd1HSAZsBQVVfeXFMTU1wV19RME85U05IOG5USENqdXI3S3NYdDFUMzg4WExGTW1BTW5qay1LbjFyd183dUl4VkFLUFk4c3ZOQ05jeTV6aFJMcFFWcFpTd01GZGtBdDNWVlZWT0lxMUpYaWdoc25xdUR2bzVvSnBJVUg1dXdKdFVjUkwxM0wzclpyc0JiM0MwUk40bjlZTkZhNi1PRDQtUU0?oc=5" target="_blank">Teladan dari Paus Leo XIV di tengah Perang Iran</a>&nbsp;&nbsp;<font color="#6f6f6f">ANTARA News</font></li><li><a href="https://news.google.com/rss/articles/CBMivAFBVV95cUxQU2hZekVma1lmaXFId1Z6bVlDVHM1WFN6cmZySXY0S1VCaG1pczNkUE9FN05OSjJFRE9sMWwzaFBJcFhEMVo2ZUZ3TXJHb1hYRDV1ZV8wNlpaYzVET1kwQ2xKeVA0aWZvbVllemg0Q2dqUTBVWElvQnFLaXVsbGQ2ZFZDeHdieFVwOTFwLWsyM3hRNG1pdHdUekdMTnVKVDA5dlNxR1lPYlBaa1JjdHdJVnBJR3hVZnNKZG5zWtIBwgFBVV95cUxQMWdDaVh0dUc0ajctS3RNN3V6VXJJaHFGNGJsYnpWMFVuUDFaT1diY09pSC1FWkJRSVJNaWJSUExpWFZ4ZFJUOG9CVzRHTmt5c2xpQ1Njd094d0I3dVc1ZkxndUctdXAxck9hTTVGNkxIZVFPbVFlaTE3cWFLNXJ4eHVMbHZ3bkM5TnhKc3loMFJKYXJ5aXJKS1A3ZkNpeFlJeXNQTmdRZ3NadFU2WEtHSHVFQlRWVFZjRlI1Y0VpRW84UQ?oc=5" target="_blank">Paus Leo Beri Warning Demokrasi Bisa Jadi Tirani, Sindir Trump?</a>&nbsp;&nbsp;<font color="#6f6f6f">CNBC Indonesia</font></li><li><a href="https://news.google.com/rss/articles/CBMipwFBVV95cUxNTElZMHU4RTBTRjA1MzNpWlRRTzhHcEJXY1p6Z1dkeW8tbzRaVURnU1BQUEl4MkpNcHJ6XzY0aGNCUy1iOHcta1Fubkl5V2xqaUx6VUR4LWZJWGpNWWJmYnJabm9aUlc1V2E3anNFdGdvcmplUUlSVkdRTW5qZWhSekZ1eG9ZTnN6OWhTUWRxQXFFR0dVUU9oUHVQR29DbTlNUGRtNDNpNA?oc=5" target="_blank">Tak Sepakat dengan Trump, Suara Paus Bukan Alat Politik</a>&nbsp;&nbsp;<font color="#6f6f6f">Enamplus</font></li><li><a href="https://news.google.com/rss/articles/CBMiogFBVV95cUxOT1h3S2w0bGpRcUF4T0ZTWUc1ZUJJNkI2X2RrRzZaeVlqNk41a2FUcWE0OERKMEV6RllhTDQwREpZSTZrQ3ZEcjlHQXlMUFRtYTE4anN5dzdINS1FUkszeG5ieVFESHNvX3Q1U3J3X3dpZ0tLWDVQVjRfcTNSRXRLSTFxeVlwa0xfTlhkeThjQjY5bXQ0U1ozazVUbVJLY1RwenfSAacBQVVfeXFMT1kteVlob0loMmVzdGF3NjAtMVpaNUxqWDN5VHVfRld4QURmMVlhVW1QeUJVZ3ZjWDI1Nmx2SzU0bF9uQVlfOGhfdVY1NkpDbU1WMFNXWC0xX2FnU2tHMnBHOGdSUkY1QzJoSTdrd2hES2VkRVJQQ3JzZFV1Vm1HUE96bjh6ZHFTZmhQT21BUEJ6SFBxdDRST1dVd2JPeWZJOF9RTEQ2LVk?oc=5" target="_blank">Ribut-ribut dengan Trump, Paus Leo Dapat Dukungan Iran</a>&nbsp;&nbsp;<font color="#6f6f6f">detikNews</font></li></ol>

In [15]:
from bs4 import BeautifulSoup

def bersihkan_html(teks):
    if pd.isna(teks):
        return ""
    soup = BeautifulSoup(teks, "html.parser")
    return soup.get_text(separator=" ").strip()

df['description_bersih'] = df['description'].apply(bersihkan_html)

# Cek hasilnya
print("SESUDAH:", df['description_bersih'][0])

SESUDAH: Trump Nyinyir Lagi: Tolong Beritahu Paus Leo, Iran Bunuh 42.000 Orang    CNN Indonesia Teladan dari Paus Leo XIV di tengah Perang Iran    ANTARA News Paus Leo Beri Warning Demokrasi Bisa Jadi Tirani, Sindir Trump?    CNBC Indonesia Tak Sepakat dengan Trump, Suara Paus Bukan Alat Politik    Enamplus Ribut-ribut dengan Trump, Paus Leo Dapat Dukungan Iran    detikNews

In [16]:
df = df.drop(columns=['guid', 'link',])

# Cek kolom yang tersisa
print(df.columns.tolist())

['id', 'title', 'source', 'tanggal', 'description', 'description_bersih']

In [17]:
df

,id,title,source,tanggal,description,description_bersih
0,1,"Trump Nyinyir Lagi: Tolong Beritahu Paus Leo, ...",CNN Indonesia,"Wed, 15 Apr 2026 06:15:03 GMT","<ol><li><a href=""https://news.google.com/rss/a...","Trump Nyinyir Lagi: Tolong Beritahu Paus Leo, ..."
1,2,"AS Kirim Kapal Perang ke Selat Hormuz, Eks KSA...",Kompas.tv,"Tue, 14 Apr 2026 12:11:00 GMT","<ol><li><a href=""https://news.google.com/rss/a...","AS Kirim Kapal Perang ke Selat Hormuz, Eks KSA..."
2,3,"Prabowo Bertemu Macron di Istana Elysee, Bahas...",CNBC Indonesia,"Tue, 14 Apr 2026 16:20:00 GMT","<ol><li><a href=""https://news.google.com/rss/a...","Prabowo Bertemu Macron di Istana Elysee, Bahas..."
3,4,Isi Chat Pelecehan Seksual 16 Mahasiswa Hukum ...,Mistar.id,"Tue, 14 Apr 2026 05:47:00 GMT","<ol><li><a href=""https://news.google.com/rss/a...",Isi Chat Pelecehan Seksual 16 Mahasiswa Hukum ...
4,5,"7 Keunggulan Oghab 44, Bandara Bawah Tanah Ira...",SINDOnews Internasional,"Wed, 15 Apr 2026 03:30:30 GMT","<ol><li><a href=""https://news.google.com/rss/a...","7 Keunggulan Oghab 44, Bandara Bawah Tanah Ira..."
...,...,...,...,...,...,...
1700,6015,"Hujan Lebat Masih Mengintai Indonesia, Ini Daf...",https://www.cnnindonesia.com/rss,"Wed, 13 May 2026 08:00:00 +0700","<img src=""https://akcdn.detik.net.id/visual/20...",BMKG memprediksi hujan lebat di sejumlah wilay...
1701,6016,"Jadi Tahanan Rumah, Nadiem Wajib Lapor dan Pak...",https://www.cnnindonesia.com/rss,"Wed, 13 May 2026 07:56:17 +0700","<img src=""https://akcdn.detik.net.id/visual/20...",Eks Mendikbud Nadiem Makarim kini menjadi taha...
1702,6017,Bebas Visa Rusia-Saudi Ternyata Tak Berlaku Bu...,https://www.cnnindonesia.com/rss,"Wed, 13 May 2026 07:55:05 +0700","<img src=""https://akcdn.detik.net.id/visual/20...",Warga Arab Saudi dan Rusia kini bisa saling ku...
1703,6018,"Ibam Divonis 4 Tahun Penjara, Giliran Nadiem H...",https://www.cnnindonesia.com/rss,"Wed, 13 May 2026 07:42:48 +0700","<img src=""https://akcdn.detik.net.id/visual/20...",Eks Mendikbud Ristek Nadiem Makarim hari ini m...
1704,6019,"Blunder Kiper Al Nassr Geger, Ronaldo Sampai M...",https://www.cnnindonesia.com/rss,"Wed, 13 May 2026 07:41:48 +0700","<img src=""https://akcdn.detik.net.id/visual/20...",Bento Matheus Krepski melakukan blunder yang b...